[versions]
kotlin = "2.1.0"
minecraft = "1.21.4"
paplin = "1.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-SNAPSHOT" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-SNAPSHOT" }
run-paper = {id = "xyz.jpenilla.run-paper", version = "2.3.1"}
plugin-yml-paper = {id = "net.minecrell.plugin-yml.paper", version = "0.6.0"}